---
- name: download {{ url }}
  run_once: true
  get_url:
    url: "{{url}}"
    dest: "{{ download }}/{{ file }}"

- name: extract {{ download }}/{{ file }}
  become: yes
  become_method: sudo
  unarchive:
    src: "{{ download }}/{{ file }}"
    dest: "{{ usr_local }}"
    copy: no
    creates: "{{ kafka_home }}"

- name: set ownership on {{ kafka_home }}
  become: yes
  become_method: sudo
  file:
    path: "{{ kafka_home }}"
    owner: vagrant
    group: vagrant
    recurse: yes
    mode: 0755

- name: set PATH=$PATH:{{ kafka_home }}/bin
  become: yes
  become_method: sudo
  lineinfile:
    dest: "{{ etc_profiles }}/kafka.sh"
    create: yes
    state: present
    regexp: '^PATH'
    line: 'PATH=$PATH:{{ kafka_home }}/bin'

- name: copy server.properties {{ kafka_home }}/config/server.properties
  template:
    src: templates/server.properties.j2
    dest: "{{ kafka_home }}/config/server.properties"
  register: kafka_config
  tags:
    - new-kafka-config

- name: create {{ kafka_log_dir }}
  file:
    path: "{{ kafka_log_dir }}"
    state: directory

- name: install kafka systemd unit file
  become: yes
  become_method: sudo
  template:
    src: templates/kafka.service.j2
    dest: "{{ system_units }}/kafka.service"
  register: kafka_service
  tags:
    - new-kafka-config

- name: export JMX Port of
  lineinfile:
    dest: "{{ kafka_home }}/bin/kafka-server-start.sh"
    insertbefore: 'exec'
    line: 'export JMX_PORT=${JMX_PORT:-9999}'

- name: restart kafka
  become: yes
  become_method: sudo
  when: kafka_config.changed or kafka_service.changed
  systemd:
    enabled: yes
    state: restarted
    name: kafka
  tags:
    - new-kafka-config

- name: add path to scripts folder
  lineinfile:
    dest: /home/vagrant/.bash_profile
    insertbefore: 'export PATH'
    line: 'PATH=/vagrant/scripts:$PATH'

